In [5]:
pip install numpy --upgrade

Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np

In [7]:
array_one = np.array([0,1,3,5,7,9])
array_one

array([0, 1, 3, 5, 7, 9])

In [8]:
num = [11,22,33,44,55,66,77]
array_two = np.array(num)
array_two

array([11, 22, 33, 44, 55, 66, 77])

In [9]:
array_of_zeroes = np.zeros((2,3))
array_of_zeroes

array([[0., 0., 0.],
       [0., 0., 0.]])

In [10]:
array_of_ones = np.ones((3,2))
array_of_ones

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [13]:
array_of_ones = np.ones((3,2) , dtype = np.int32)
array_of_ones

array([[1, 1],
       [1, 1],
       [1, 1]])

In [14]:
array_empty = np.empty((3,2))
array_empty

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [17]:
array_eye = np.eye(4)
array_eye
#Para criar matriz quadradas

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [18]:
array_of_evens = np.arange(2,24,2)
array_of_evens
# os argumentos passados são: o limite inferior da matriz
#o limite superior e o intervalo, nesse caso a matriz irá iniciar com o elemento 2
# e cada elemento será 2x maior do que ele até que o 24 seja atingido

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])